// Code generated by mockery v2.9.4. DO NOT EDIT.

package mock

import (
	mock "github.com/stretchr/testify/mock"

	v1alpha1 "github.com/epam/edp-jenkins-operator/v2/pkg/apis/v2/v1alpha1"
)

// JenkinsFolderHandler is an autogenerated mock type for the JenkinsFolderHandler type
type JenkinsFolderHandler struct {
	mock.Mock
}

// ServeRequest provides a mock function with given fields: jf
func (_m *JenkinsFolderHandler) ServeRequest(jf *v1alpha1.JenkinsFolder) error {
	ret := _m.Called(jf)

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1alpha1.JenkinsFolder) error); ok {
		r0 = rf(jf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
