apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: jenkinsfolders.v2.edp.epam.com
spec:
  group: v2.edp.epam.com
  names:
    kind: JenkinsFolder
    listKind: JenkinsFolderList
    plural: jenkinsfolders
    singular: jenkinsfolder
    shortNames:
      - jf
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            codebaseName:
              description: 'Property indicates which codebase cr should be taken to trigger job build with correct parameters.'
              anyOf:
                - type: null
                - type: string
            ownerName:
              description: 'Property indicates which jenkins car should be taken to initialize correct client.'
              anyOf:
                - type: null
                - type: string
            job:
              properties:
                name:
                  description: 'Property indicates job name.'
                  type: string
                config:
                  description: 'Contains config for triggering Job provision.'
                  type: string
              required:
                - name
                - config
          type: object