apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: jenkinsjobs.v2.edp.epam.com
spec:
  group: v2.edp.epam.com
  names:
    kind: JenkinsJob
    listKind: JenkinsJobList
    plural: jenkinsjobs
    singular: jenkinsjob
    shortNames:
      - jj
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            ownerName:
              description: 'Property indicates which jenkins cr should be taken to initialize correct client.'
              anyOf:
                - type: null
                - type: string
            stageName:
              description: 'Property indicates which stage cr should be taken to create correct pipeline in jenkins.'
              anyOf:
                - type: null
                - type: string
            jenkinsFolder:
              description: 'Property indicates name of folder for current stage.'
              anyOf:
                - type: null
                - type: string
            job:
              properties:
                name:
                  description: 'Property indicates job name.'
                  type: string
                config:
                  description: 'Contains config template to create pipeline in Jenkins.'
                  type: string
              required:
                - name
                - config
          type: object