apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cdstagejenkinsdeployments.v2.edp.epam.com
spec:
  group: v2.edp.epam.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                job:
                  type: string
                tag:
                  type: object
                  properties:
                    codebase:
                      type: string
                    tag:
                      type: string
                  required:
                    - codebase
                    - tag
            status:
              type: object
              additionalProperties: true
      subresources:
        status: { }
  conversion:
    strategy: None
  scope: Namespaced
  names:
    plural: cdstagejenkinsdeployments
    singular: cdstagejenkinsdeployment
    kind: CDStageJenkinsDeployment
    shortNames:
      - csjd
