{{- if .Values.jenkins.deploy -}}
apiVersion: v2.edp.epam.com/v1alpha1
kind: Jenkins
metadata:
  name: jenkins
spec:
  edpSpec:
    dnsWildcard: {{ .Values.global.dnsWildCard }}
    {{- if .Values.jenkins.imagePullSecrets}}
    imagePullSecrets:
      {{- range .Values.jenkins.imagePullSecrets }}
      - {{. -}}
      {{- end -}}
    {{end}}
  image: {{.Values.jenkins.image}}
  version: {{.Values.jenkins.version}}
  initImage: {{.Values.jenkins.initImage}}
  {{- if .Values.jenkins.basePath }}
  basePath: "{{ .Values.jenkins.basePath }}"
  {{- end }}
  volumes:
    - name: "data"
      storageClass: {{ .Values.jenkins.storage.class }}
      capacity: {{ .Values.jenkins.storage.size }}
  sharedLibraries:
    {{- range .Values.jenkins.sharedLibraries}}
    - name: {{ toYaml .name}}
      url: {{ toYaml .url}}
      tag: {{ toYaml .tag}}
      {{- if .secret}}
      secret: {{ toYaml .secret}}
      type: {{ toYaml .type}}
      {{- end}}
    {{- end}}
  keycloakSpec:
    enabled: true
    realm: "{{ .Values.global.edpName }}-main"
{{end}}
