// Code generated by mockery v2.9.4. DO NOT EDIT.

package mock

import (
	mock "github.com/stretchr/testify/mock"

	jenkinsApi "github.com/epam/edp-jenkins-operator/v2/pkg/apis/v2/v1"
)

// JenkinsService is an autogenerated mock type for the JenkinsService type
type JenkinsService struct {
	mock.Mock
}

// Configure provides a mock function with given fields: instance
func (_m *JenkinsService) Configure(instance *jenkinsApi.Jenkins) (*jenkinsApi.Jenkins, bool, error) {
	ret := _m.Called()

	var r0 *jenkinsApi.Jenkins
	if rf, ok := ret.Get(0).(func(jenkinsApi.Jenkins) *jenkinsApi.Jenkins); ok {
		r0 = rf(*instance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jenkinsApi.Jenkins)
		}
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(jenkinsApi.Jenkins) bool); ok {
		r1 = rf(*instance)
	} else {
		r1 = ret.Get(1).(bool)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(jenkinsApi.Jenkins) error); ok {
		r2 = rf(*instance)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// CreateAdminPassword provides a mock function with given fields: instance
func (_m *JenkinsService) CreateAdminPassword(instance *jenkinsApi.Jenkins) error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func(jenkinsApi.Jenkins) error); ok {
		r0 = rf(*instance)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExposeConfiguration provides a mock function with given fields: instance
func (_m *JenkinsService) ExposeConfiguration(instance jenkinsApi.Jenkins) (*jenkinsApi.Jenkins, bool, error) {
	ret := _m.Called()

	var r0 *jenkinsApi.Jenkins
	if rf, ok := ret.Get(0).(func(jenkinsApi.Jenkins) *jenkinsApi.Jenkins); ok {
		r0 = rf(instance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jenkinsApi.Jenkins)
		}
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(jenkinsApi.Jenkins) bool); ok {
		r1 = rf(instance)
	} else {
		r1 = ret.Get(1).(bool)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(jenkinsApi.Jenkins) error); ok {
		r2 = rf(instance)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Integration provides a mock function with given fields: instance
func (_m *JenkinsService) Integration(instance *jenkinsApi.Jenkins) (*jenkinsApi.Jenkins, bool, error) {
	ret := _m.Called()

	var r0 *jenkinsApi.Jenkins
	if rf, ok := ret.Get(0).(func(jenkinsApi.Jenkins) *jenkinsApi.Jenkins); ok {
		r0 = rf(*instance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jenkinsApi.Jenkins)
		}
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(jenkinsApi.Jenkins) bool); ok {
		r1 = rf(*instance)
	} else {
		r1 = ret.Get(1).(bool)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(jenkinsApi.Jenkins) error); ok {
		r2 = rf(*instance)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// IsDeploymentReady provides a mock function with given fields: instance
func (_m *JenkinsService) IsDeploymentReady(instance jenkinsApi.Jenkins) (bool, error) {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func(jenkinsApi.Jenkins) bool); ok {
		r0 = rf(instance)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(jenkinsApi.Jenkins) error); ok {
		r1 = rf(instance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
