apiVersion: v2
description: A Helm chart for EDP Jenkins Operator
home: https://solutionshub.epam.com/solution/epam-delivery-platform
name: jenkins-operator
type: application
version: 2.8.0-SNAPSHOT
appVersion: 2.8.0-SNAPSHOT
maintainers:
  - name: EPAM EDP Team
sources:
  - https://github.com/epam/edp-jenkins-operator
