// Code generated by mockery v2.9.4. DO NOT EDIT.

package mock

import (
	mock "github.com/stretchr/testify/mock"

	v1alpha1 "github.com/epam/edp-jenkins-operator/v2/pkg/apis/v2/v1alpha1"
)

// JenkinsJobHandler is an autogenerated mock type for the JenkinsJobHandler type
type JenkinsJobHandler struct {
	mock.Mock
}

// ServeRequest provides a mock function with given fields: jj
func (_m *JenkinsJobHandler) ServeRequest(jj *v1alpha1.JenkinsJob) error {
	ret := _m.Called(jj)

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1alpha1.JenkinsJob) error); ok {
		r0 = rf(jj)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
