apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: edp-jenkins-role
rules:
  - apiGroups: ["*"] # "" indicates the core API group
    resources: ["codebases", "codebasebranches", "codebaseimagestreams", "cdpipelines", "nexuses", "stages",
                "gitservers", "adminconsoles", "jenkinses", "jenkins", "edpcomponents", "keycloakrealms",
                "jirafixversions", "codebases/finalizers", "jiraissuemetadatas", "jiraissuemetadatas/finalizers",
                "jiraissuemetadatas/status"]
    verbs: ["get", "create", "update", "patch", "list", "delete"]