{{ if eq .Values.global.platform "kubernetes" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "jenkins-operator.labels" . | nindent 4 }}
  name: edp-{{ .Values.global.edpName }}-jenkins
rules:
- apiGroups:
    - "*"
  resources:
    - podsecuritypolicies
  verbs:
    - get
    - list
    - update
- apiGroups:
    - "*"
  resources:
    - namespaces
  verbs:
    - create
    - get
{{ end }}
