apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "jenkins-operator.labels" . | nindent 4 }}
  name: edp-{{ .Values.global.edpName }}-jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: edp-{{ .Values.global.edpName }}-jenkins
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: {{ .Values.global.edpName }}