name: Go

on:
  push:
    branches: [ master ]

env:
  GOLANG_VERSION: '1.18'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Upload codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          file: coverage.out